### ISSUE TITLE
Error in 'help skill' command

### ISSUE THREAD

**Issue by ScrambledBits** [opsdroid/skill-devtools#3]
I'm having an error when trying to invoke the _help skill_ command, from the logs I see:

```
DEBUG websockets.protocol: client < Frame(fin=True, opcode=1, data=b'{"text":"Check the log for details","username":"MyBot","icons":{"emoji":":smile:","image_64":"https:\\/\\/a.slack-edge.com\\/37d58\\/img\\/emoji_2017_12_06\\/apple\\/1f604.png"},"bot_id":"XXXXXXX","type":"message","subtype":"bot_message","team":"T039ZEK3W","bot_profile":{"id":"BFGDX163X","deleted":false,"name":"bot","updated":1547737556,"app_id":"A0F7YS25R","icons":{"image_36":"https:\\/\\/a.slack-edge.com\\/7f1a0\\/plugins\\/bot\\/assets\\/service_36.png","image_48":"https:\\/\\/a.slack-edge.com\\/7f1a0\\/plugins\\/bot\\/assets\\/service_48.png","image_72":"https:\\/\\/a.slack-edge.com\\/7f1a0\\/plugins\\/bot\\/assets\\/service_72.png"},"team_id":"XXXXXXX"},"source_team":"XXXXXXX","channel":"XXXXXXXX","event_ts":"1547747909.001100","ts":"1547747909.001100"}', rsv1=False, rsv2=False, rsv3=False)
ERROR opsdroid.core: Exception when running skill 'devtools' 
Traceback (most recent call last):
  File "/home/User/p3-env/lib/python3.7/site-packages/opsdroid-0.13.0+65.g06a71ea-py3.7.egg/opsdroid/core.py", line 315, in run_skill
    await skill(self, config, message)
  File "/home/User/opsdroid-skills/opsdroid-modules/skill/devtools/__init__.py", line 55, in help_skill
    if opsdroid.skills[i]['config']['name'] not in skill_names:
TypeError: 'function' object is not subscriptable
DEBUG websockets.protocol: client < Frame(fin=True, opcode=1, data=b'{"type":"desktop_notification","title":"My Workspace","subtitle":"MyBot (bot)","msg":"1547747908.001000","ts":"1547747908.001000","content":"Whoops there has been an error","channel":"XXXXXXXXXX","launchUri":"slack:\\/\\/channel?id=XXXXXXXXXX&message=1547747908001000&team=XXXXXXXXX","avatarImage":null,"ssbFilename":"knock_brush.mp3","imageUri":null,"is_shared":true,"event_ts":"1547747909.000800"}', rsv1=False, rsv2=False, rsv3=False)
```

The important part wouold be:

```
ERROR opsdroid.core: Exception when running skill 'devtools' 
Traceback (most recent call last):
  File "/home/User/p3-env/lib/python3.7/site-packages/opsdroid-0.13.0+65.g06a71ea-py3.7.egg/opsdroid/core.py", line 315, in run_skill
    await skill(self, config, message)
  File "/home/User/opsdroid-skills/opsdroid-modules/skill/devtools/__init__.py", line 55, in help_skill
    if opsdroid.skills[i]['config']['name'] not in skill_names:
TypeError: 'function' object is not subscriptable
```

How can this be fixed?

**Comment by jacobtomlinson** [comment]
Thanks for raising this! Which version of opsdroid are you running?

**Comment by ScrambledBits** [comment]
I compiled from master because the latest version in PyPi had a bug where it wouldn't shutdown properly and instead raised a bunch of zombie processes, ultimately hogging all resources on the host. That has apparently been fixed in the latest code in master.

**Comment by jacobtomlinson** [comment]
That makes sense. There were some breaking changes on master which will be covered in the next release. It looks like this skill will be affected by them.

**Comment by cupen** [comment]
opsdroid v0.15.4

+1

my trace log
```
INFO opsdroid.database.sqlite: Connected to sqlite /home/cupen/.local/share/opsdroid/sqlite.db
INFO opsdroid.core: Opsdroid is now running, press ctrl+c to exit.
INFO opsdroid.web: Started web server on http://127.0.0.1:8081
INFO aiohttp.access: 127.0.0.1 [17/Jul/2019:13:21:11 +0000] "POST /connector/websocket HTTP/1.1" 200 252 "-" "-"
ERROR opsdroid.core: Exception when running skill 'devtools' 
Traceback (most recent call last):
  File "/home/cupen/.local/share/virtualenvs/opsdroid-skills-XMdUEVC6/lib/python3.7/site-packages/opsdroid/core.py", line 346, in run_skill
    await skill(self, config, message)
  File "/home/cupen/.local/share/opsdroid/opsdroid-modules/skill/devtools/__init__.py", line 55, in help_skill
    if opsdroid.skills[i]['config']['name'] not in skill_names:
TypeError: 'function' object is not subscriptable


```

**Comment by jacobtomlinson** [comment]
I think it should be `opsdroid.skills[i].config['name']` now. Fancy raising a PR?
